#@ load("@ytt:data", "data")
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
  - image: controller:latest
    path: .
    pack:
      build:
        builder: paketobuildpacks/builder:tiny
destinations:
  - image: controller:latest
    newImage: #@ data.values.build.registry_host + "/" + data.values.build.registry_project + "/monorepository-controller"
